version: '0.2'
addresses:
  github@<username>.mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
triggers:
  - name: github-action-failed
    composition:
      - criteria:
          metadata.github.pr.buildFailed: true
actions:
  - name: mylaptop
    type: daemon
    config:
      daemon: mylaptop
  - name: forward-github-to-personal-email
    type: mailscript-email
    config:
      key: owner
      from: github@<username>.mailscript.com
      forward: <personal-email>
      type: forward
workflows:
  - name: github-action-failures-to-daemon
    input: github@<username>.mailscript.com
    trigger: github-action-failed-trigger
    action: mylaptop
