version: "0.2"
addresses:
  kanej@mailscript.io:
    keys:
      - name: owner
        read: true
        write: true
triggers: []
actions:
  - name: macmini
    type: daemon
    config:
      daemon: macmini
workflows:
  - name: github-to-daemon
    input: smith@mailscript.io
    action: macmini
